### ISSUE TITLE
Allow multi-character identifiers and special symbols as identifiers for definitions

### ISSUE THREAD

**Issue by anton-trunov** [evinism/lambda-explorer#42]
IMHO, `Add := λmn. m S n` or `+ := λmn. m S n` are more suggestive compared to one-letter identifiers like `A`.

**Comment by evinism** [comment]
Allowing multicharacter variable names has been one of the more annoying problems that I haven't quite figured out yet-- how do we deal with the ambiguity of saying `SUCC` being one variable, vs. `((SU)C)C`, while still keeping the metalanguage relatively small and succinct?

Options are:
- let the lexer look up to see if a symbol (like SUCC) exists in the execution context before lexing as `(((S)U)C)C`
- require whitespace around single letter variable names
- something else??

I don't personally like either of those two options, but I'm leaning towards the second one, it seems to be done half the time anyways, or whenever ambiguity pops up.

As for certain special characters, we can just whitelist those.

**Comment by anton-trunov** [comment]
What about a special case where words starting with a capital letter are tokenized as a single identifier? `SUCC`, `Succ`, etc. It seem like people almost never use uppercase letters under lambdas.

**Comment by evinism** [comment]
implemented in https://github.com/evinism/lambda-explorer/pull/55, merging after green

**Comment by evinism** [comment]
implemented here https://github.com/evinism/lambda-explorer/pull/71
